### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by envygeeks** [envygeeks/atom-comment-headers#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.197.0-f8047ba
**System**: linux 3.13.0-51-generic
**Thrown From**: [comment-headers](https://github.com/envygeeks/atom-comment-headers) package, v2.8.0
### Stack Trace

Uncaught RangeError: Invalid array length

```
At /home/jordon/.atom/packages/comment-headers/index.js:57

RangeError: Invalid array length
  at Object.module.exports.insertCommentHeader (/home/jordon/.atom/packages/comment-headers/index.js:57:11)
  at Object.module.exports.insert (/home/jordon/.atom/packages/comment-headers/index.js:36:16)
  at atom-text-editor.atom.commands.add.comment-headers:insert (/home/jordon/.atom/packages/comment-headers/index.js:6:23)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/github/atom/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /opt/github/atom/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/github/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/github/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/github/atom/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
  2x -1:05.6.0 editor:newline (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -1:04.5.0 comment-headers:insert (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
  2x -1:03.4.0 core:undo (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
  2x -1:02.4.0 core:save (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:29.5.0 core:close (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:23.7.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
  7x -0:07.2.0 comment-headers:insert (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
  2x -0:04.6.0 core:close (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
  2x -0:02.0 editor:newline (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
  2x -0:01.2.0 core:move-up (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:00.7.0 comment-headers:insert (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".bundle",
      "tmp",
      "log",
      "db/*.sqlite3",
      "*.map",
      "node_modules",
      "*.mp4",
      "*.mkv",
      "*.avi",
      "Gemfile.lock",
      "vendor/bundle",
      "_site",
      ".app",
      ".dockerignore",
      "config.ru",
      ".version"
    ],
    "disabledPackages": [
      "welcome",
      "exception-reporting",
      "feedback",
      "metrics",
      "styleguide",
      "release-notes",
      "background-tips",
      "color",
      "inline-autocomplete",
      "autoflow"
    ],
    "themes": [
      "one-light-ui",
      "github-2014"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.9
block-cursor, v0.12.5
comment-headers, v2.8.0
editorconfig, v1.0.0
file-icons, v1.5.5
github-2014, v3.1.0
language-docker, v1.1.3
language-haml, v0.20.0
language-liquid, v0.2.0
language-nginx, v0.5.2
language-rspec, v0.3.0
language-slim, v0.4.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-ruby, v0.1.4
ruby-block, v0.3.3
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by envygeeks** [comment]
This was a bug with a bad reload from Atom for some reason...
